version: '3.7'

services:

  nginx:
    image: nginx:1.15-alpine
    depends_on:
     - demo
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./docker/certbot/conf:/etc/letsencrypt
      - ./docker/certbot/www:/var/www/certbot
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
    restart: unless-stopped

  certbot:
    image: certbot/certbot
    volumes:
      - ./docker/certbot/conf:/etc/letsencrypt
      - ./docker/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    restart: unless-stopped

  coturn:
    image: instrumentisto/coturn
    ports:
      - "3478:3478"
      - "3479:3479"
      - "5349:5349"
      - "5350:5350"
    #network_mode: "host"
    volumes:
      - ./docker/coturn/turnserver.conf:/etc/coturn/turnserver.conf
      - ./docker/coturn/db:/var/db/turndb:ro
      - ./docker/certbot/conf:/etc/letsencrypt
      - ./docker/coturn/coturn:/etc/default/coturn

  demo:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/usr/src/app
    dns: 8.8.8.8
    ports:
      - "8000:8000"
    environment:
      NODE_ENV: production
    restart: unless-stopped
